# dependabot config
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    ignore:
      # update too often, ignore patch releases
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-patch"]
    groups:
      jest-monorepo:
        patterns:
          - "jest"
          - "jest-circus"
    unknown-key:
      foo-bar: "baz"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
